#! /bin/bash

for rmax in $(seq 0.30 0.01 0.41); do
    for r1norm in $(seq 0.74 0.01 0.77); do
        for pot in $(seq -43 1 -39); do
            echo -en "$rmax\t$r1norm\t$pot\t"
            scripts/run_get_pitch.sh $rmax $r1norm $pot | grep TOTAL
        done
    done
done | sort -t: -k2n